/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Ricky
 */
public class GerenciarLivros extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarLivros
     */
    public GerenciarLivros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSPainelTabela = new javax.swing.JScrollPane();
        jtLivro = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jcTipoDePesquisa = new javax.swing.JComboBox<>();
        txtPesquisar = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtEdicao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtEditora = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAutor1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbInserir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jbConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 400));

        jSPainelTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSPainelTabelaMouseClicked(evt);
            }
        });

        jtLivro.setAutoCreateRowSorter(true);
        jtLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Título", "Autor", "Editora", "Edição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLivroMouseClicked(evt);
            }
        });
        jtLivro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtLivroKeyReleased(evt);
            }
        });
        jSPainelTabela.setViewportView(jtLivro);
        jtLivro.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel7.setText("Pesquisar por:");

        jcTipoDePesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISBN", "Autor", "Título" }));
        jcTipoDePesquisa.setSelectedIndex(2);
        jcTipoDePesquisa.setToolTipText("");

        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jButton1.setText("Exemplares");
        jButton1.setToolTipText("Exibe lista de exemplares do item selecionado");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtEdicao.setEnabled(false);

        jLabel5.setText("Edição");

        jLabel2.setText("Autor");

        txtAutor.setEnabled(false);
        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        txtEditora.setEnabled(false);
        txtEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditoraActionPerformed(evt);
            }
        });

        txtTitulo.setEnabled(false);

        jLabel4.setText("Título");

        jLabel3.setText("Editora");

        txtAutor1.setEnabled(false);
        txtAutor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutor1ActionPerformed(evt);
            }
        });

        jLabel6.setText("ISBN");

        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.setEnabled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.setEnabled(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jbConfirmar.setText("Confirmar");
        jbConfirmar.setEnabled(false);
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(txtAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jbInserir)
                        .addGap(168, 168, 168)
                        .addComponent(jbAlterar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBCancelar)
                        .addGap(47, 47, 47)
                        .addComponent(jbConfirmar))
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbExcluir)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)))
                .addGap(4, 4, 4)
                .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txtAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(txtEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbInserir)
                            .addComponent(jbExcluir)
                            .addComponent(jbAlterar))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBCancelar)
                            .addComponent(jbConfirmar))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcTipoDePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSPainelTabela))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPainelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jcTipoDePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLivroMouseClicked
        if(jtLivro.getSelectedRow()!= -1){
            txtNumeroDeTombo.setText(jtLivro.getValueAt(jtLivro.getSelectedRow(), 0).toString());
            txtTitulo.setText(jtLivro.getValueAt(jtLivro.getSelectedRow(), 1).toString());
            txtAutor.setText(jtLivro.getValueAt(jtLivro.getSelectedRow(), 2).toString());
            txtEditora.setText(jtLivro.getValueAt(jtLivro.getSelectedRow(), 3).toString());
            txtEdicao.setText(jtLivro.getValueAt(jtLivro.getSelectedRow(), 4).toString());
            jcStatus.setSelectedItem(jtLivro.getValueAt(jtLivro.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_jtLivroMouseClicked

    private void jtLivroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtLivroKeyReleased
        if(jtLivro.getSelectedRow()!= -1){
            txtNumeroDeTombo.setText(jtLivro.getValueAt(jtLivro.getSelectedRow(), 0).toString());
            txtAutor.setText(jtLivro.getValueAt(jtLivro.getSelectedRow(), 1).toString());
            txtEditora.setText(jtLivro.getValueAt(jtLivro.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_jtLivroKeyReleased

    private void jSPainelTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSPainelTabelaMouseClicked
        if(jtLivro.getSelectedRow()!= -1){
            txtNumeroDeTombo.setText(jtLivro.getValueAt(jtLivro.getSelectedRow(), 0).toString());
            txtAutor.setText(jtLivro.getValueAt(jtLivro.getSelectedRow(), 1).toString());
            txtEditora.setText(jtLivro.getValueAt(jtLivro.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_jSPainelTabelaMouseClicked

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed

        int p =verificarCampoPesquisar();

        System.out.println(p + " p");
        livro.setPesquisa(txtPesquisar.getText());
        BeansLivro model =  dao.buscaLivro(livro);
        //        txtNumeroDeTombo.setText(String.valueOf(model.getNumeroDeTombo()));
        if(p==0 && dao.buscaLivro(livro) != null && jcTipoDePesquisa.getSelectedItem().toString()=="Número de tombo" ){

            System.out.println(jcTipoDePesquisa.getSelectedItem().toString());
            txtNumeroDeTombo.setText(String.valueOf(model.getNumeroDeTombo()));
            txtTitulo.setText(model.getTitulo());
            txtAutor.setText(model.getAutor());
            txtEditora.setText(model.getEditora());
            txtEdicao.setText(String.valueOf(model.getEdicao()));
            jcStatus.setSelectedItem(model.getStatus());
            jtLivro.setVisible(true);
            jbAlterar.setEnabled(true);
            jbExcluir.setEnabled(true);
            jbInserir.setEnabled(!true);
            jBCancelar.setEnabled(true);
            livro.setPesquisa("");
            //preencherTabela("SELECT  numeroDeTombo, titulo, autor, editora, edicao, status " + "FROM livros " +"WHERE " +"(titulo ='" + livro.getPesquisa() + "')");
            preencherTabela("select * from livros where numeroDeTombo = " + livro.getNumeroDeTombo());
            txtPesquisar.setText("");
        }else if(p==0 && jcTipoDePesquisa.getSelectedItem().toString()=="Título" ){
            System.out.println(jcTipoDePesquisa.getSelectedItem().toString());
            jtLivro.setVisible(true);
            jbAlterar.setEnabled(true);
            jbExcluir.setEnabled(true);
            jbInserir.setEnabled(!true);
            jBCancelar.setEnabled(true);
            livro.setPesquisa("");
            //preencherTabela("SELECT  numeroDeTombo, titulo, autor, editora, edicao, status " + "FROM livros " +"WHERE " +"(titulo ='" + livro.getPesquisa() + "')");
            preencherTabela("SELECT * FROM `livros` WHERE titulo LIKE '%" + txtPesquisar.getText()+"%'");
            txtPesquisar.setText("");

        }else{
            JOptionPane.showMessageDialog(null, "Item não encontrado!");
            jtLivro.setVisible(false);
            txtPesquisar.setText("");
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void txtEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditoraActionPerformed

    private void txtAutor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutor1ActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        flag = 1;
        jbConfirmar.setEnabled(true);
        txtNumeroDeTombo.setEnabled(true);
        txtTitulo.setEnabled(true);
        txtAutor.setEnabled(true);
        txtEditora.setEnabled(true);
        txtEdicao.setEnabled(true);
        jcStatus.setEnabled(true);
        jBCancelar.setEnabled(true);
    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        flag =2;
        jtLivro.setEnabled(false);
        jbConfirmar.setEnabled(true);
        txtNumeroDeTombo.setEnabled(!true);
        txtTitulo.setEnabled(true);
        txtAutor.setEnabled(true);
        txtEditora.setEnabled(true);
        txtEdicao.setEnabled(true);
        jcStatus.setEnabled(true);
        jBCancelar.setEnabled(true);
        jbAlterar.setEnabled(false);
        jbInserir.setEnabled(false);
        jbExcluir.setEnabled(false);
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        flag =3;
        jbConfirmar.setEnabled(true);
        txtNumeroDeTombo.setEnabled(false);
        txtTitulo.setEnabled(false);
        txtAutor.setEnabled(false);
        txtEditora.setEnabled(false);
        txtEdicao.setEnabled(false);
        jcStatus.setEnabled(false);
        jBCancelar.setEnabled(true);
        jbAlterar.setEnabled(false);
        jbInserir.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbConfirmar.setEnabled(true);

    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed

        jbConfirmar.setEnabled(!true);
        txtNumeroDeTombo.setEnabled(!true);
        txtTitulo.setEnabled(!true);
        txtAutor.setEnabled(!true);
        txtEditora.setEnabled(!true);
        txtEdicao.setEnabled(!true);
        jcStatus.setEnabled(!true);
        jBCancelar.setEnabled(!true);
        limparCampos();
        jbInserir.setEnabled(true);
        jbAlterar.setEnabled(!true);
        jbExcluir.setEnabled(!true);

        /*if(jtLivro.getSelectedRow()!= -1){
            jtLivro.setValueAt(txtNumeroDeTombo.getText(),jtLivro.getSelectedRow(), 0);
            jtLivro.setValueAt(txtAutor.getText(),jtLivro.getSelectedRow(), 1);
            jtLivro.setValueAt(txtEditora.getText(),jtLivro.getSelectedRow(), 2);

        }*/
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        int r = verificarCampos();
        livro.setPesquisa(txtPesquisar.getText());
        BeansLivro model =  dao.buscaLivro(livro);
        if(flag==1 && r !=1){

            livro.setNumeroDeTombo((Integer.parseInt(txtNumeroDeTombo.getText())));
            livro.setTitulo(txtTitulo.getText());
            livro.setAutor(txtAutor.getText());
            livro.setEditora(txtEditora.getText());
            livro.setEdicao((Integer.parseInt(txtEdicao.getText())));
            livro.setStatus("Ativo");

            dao.salvar(livro);

            limparCampos();
            preencherTabela("select * from livros order by numeroDeTombo");
            txtNumeroDeTombo.setEnabled(false);
            txtTitulo.setEnabled(false);
            txtAutor.setEnabled(false);
            txtEditora.setEnabled(false);
            txtEdicao.setEnabled(false);
            jcStatus.setEnabled(false);
            jbConfirmar.setEnabled(false);

        }else if (flag == 2 && r!=1){
            livro.setNumeroDeTombo((Integer.parseInt(txtNumeroDeTombo.getText())));
            livro.setTitulo(txtTitulo.getText());
            livro.setAutor(txtAutor.getText());
            livro.setEditora(txtEditora.getText());
            livro.setEdicao((Integer.parseInt(txtEdicao.getText())));
            livro.setStatus((String)jcStatus.getSelectedItem());
            dao.editar(livro);
            limparCampos();
            preencherTabela("select * from livros order by numeroDeTombo");
            txtNumeroDeTombo.setEnabled(false);
            txtTitulo.setEnabled(false);
            txtAutor.setEnabled(false);
            txtEditora.setEnabled(false);
            txtEdicao.setEnabled(false);
            jcStatus.setEnabled(false);
            jbConfirmar.setEnabled(false);
            jbInserir.setEnabled(true);
        }else if (flag == 3 && r!=1){

            dao.excluir(livro);
            limparCampos();
            preencherTabela("select * from livros order by numeroDeTombo");
            txtNumeroDeTombo.setEnabled(false);
            txtTitulo.setEnabled(false);
            txtAutor.setEnabled(false);
            txtEditora.setEnabled(false);
            txtEdicao.setEnabled(false);
            jcStatus.setEnabled(false);
            jbConfirmar.setEnabled(false);
            jbInserir.setEnabled(true);
            jbAlterar.setEnabled(true);
            jbExcluir.setEnabled(true);

        }

    }//GEN-LAST:event_jbConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jSPainelTabela;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JComboBox<String> jcTipoDePesquisa;
    private javax.swing.JTable jtLivro;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAutor1;
    private javax.swing.JTextField txtEdicao;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
