/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Ricky
 */
public class GerenciarPolitica extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GerenciarPolitica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMultaPorDinheiro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQtdItens = new javax.swing.JTextField();
        txtNomePolitica = new javax.swing.JTextField();
        txtPesquisar = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtQtdDia = new javax.swing.JTextField();
        jsMultaEmDias = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSPainelTabela = new javax.swing.JScrollPane();
        jtPolitica = new javax.swing.JTable();
        jbInserir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jbConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 400));

        txtMultaPorDinheiro.setEnabled(false);
        txtMultaPorDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMultaPorDinheiroActionPerformed(evt);
            }
        });

        jLabel3.setText("Multa em diinheiro:");

        jLabel2.setText("Quantidade de itens:");

        txtQtdItens.setEnabled(false);

        txtNomePolitica.setEnabled(false);
        txtNomePolitica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePoliticaActionPerformed(evt);
            }
        });

        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade de dias:");

        txtQtdDia.setEnabled(false);

        jsMultaEmDias.setEnabled(false);
        jsMultaEmDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsMultaEmDiasActionPerformed(evt);
            }
        });

        jLabel6.setText("Multa em dias");

        jLabel1.setText("Nome:");

        jSPainelTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSPainelTabelaMouseClicked(evt);
            }
        });

        jtPolitica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Quantidade de dias", "Quantidade de itens", "Multa em dias", "Multa em dinheiro", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPolitica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPoliticaMouseClicked(evt);
            }
        });
        jtPolitica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPoliticaKeyReleased(evt);
            }
        });
        jSPainelTabela.setViewportView(jtPolitica);

        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.setEnabled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.setEnabled(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jbConfirmar.setText("Confirmar");
        jbConfirmar.setEnabled(false);
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMultaPorDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtQtdItens, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)
                                        .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jBCancelar)
                                        .addGap(40, 40, 40)
                                        .addComponent(jbConfirmar)
                                        .addGap(35, 35, 35))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtNomePolitica, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPesquisar)
                                .addGap(75, 75, 75))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jsMultaEmDias, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQtdDia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(156, 156, 156))
                    .addComponent(jLabel1))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSPainelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jSPainelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomePolitica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtQtdItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMultaPorDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtQtdDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jsMultaEmDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBCancelar)
                            .addComponent(jbConfirmar))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMultaPorDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMultaPorDinheiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMultaPorDinheiroActionPerformed

    private void txtNomePoliticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePoliticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePoliticaActionPerformed

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        politica.setPesquisa(txtPesquisar.getText());
        BeansPolitica model =  daoPolitica.buscaPolitica(politica);
        int p =verificarCampoPesquisar();

        System.out.println(p + " p");

        if(p==0  ){

            preencherTabela("SELECT * FROM `politicas` WHERE Nome LIKE '%" + politica.getPesquisa()+"%'");
            jtPolitica.setVisible(true);
            jbAlterar.setEnabled(true);
            jbExcluir.setEnabled(true);
            jbInserir.setEnabled(!true);
            jBCancelar.setEnabled(true);
            jtPolitica.setRowSelectionAllowed(true);
            politica.setPesquisa("");
            txtPesquisar.setText("");
        }else {
            JOptionPane.showMessageDialog(null, "Item não encontrado!");
            jtPolitica.setVisible(false);
            txtPesquisar.setText("");

        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jsMultaEmDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsMultaEmDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsMultaEmDiasActionPerformed

    private void jtPoliticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPoliticaMouseClicked
        if(jtPolitica.getSelectedRow()!= -1){
            txtNomePolitica.setText(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 0).toString());
            txtQtdDia.setText(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 1).toString());
            txtQtdItens.setText(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 2).toString());
            jsMultaEmDias.setText(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 3).toString());
            txtMultaPorDinheiro.setText(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_jtPoliticaMouseClicked

    private void jtPoliticaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPoliticaKeyReleased
        if(jtPolitica.getSelectedRow()!= -1){
            txtNomePolitica.setText(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 0).toString());
            txtQtdDia.setText(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 1).toString());
            txtQtdItens.setText(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 2).toString());
            jsMultaEmDias.setText(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 3).toString());
            txtMultaPorDinheiro.setText(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_jtPoliticaKeyReleased

    private void jSPainelTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSPainelTabelaMouseClicked
        if(jtPolitica.getSelectedRow()!= -1){
            txtNomePolitica.setText(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 0).toString());
            txtQtdItens.setText(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 1).toString());
            txtMultaPorDinheiro.setText(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 2).toString());
            politica.setStatus(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 3).toString());

        }

    }//GEN-LAST:event_jSPainelTabelaMouseClicked

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        flag = 1;
        jbConfirmar.setEnabled(true);
        txtNomePolitica.setEnabled(true);
        txtQtdDia.setEnabled(true);
        txtQtdItens.setEnabled(true);
        txtMultaPorDinheiro.setEnabled(true);
        txtPesquisar.setEnabled(false);
        jbPesquisar.setEnabled(false);
        jBCancelar.setEnabled(true);
        jsMultaEmDias.setEnabled(true);
    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        flag =2;
        jtPolitica.setEnabled(false);
        jbConfirmar.setEnabled(true);
        txtNomePolitica.setEnabled(!true);
        txtQtdDia.setEnabled(true);
        txtQtdItens.setEnabled(true);
        txtMultaPorDinheiro.setEnabled(true);
        jsMultaEmDias.setEnabled(true);
        jBCancelar.setEnabled(true);
        jbAlterar.setEnabled(false);
        jbInserir.setEnabled(false);
        jbExcluir.setEnabled(false);
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        flag =3;
        jbConfirmar.setEnabled(true);
        txtNomePolitica.setEnabled(false);
        txtQtdDia.setEnabled(false);
        txtQtdItens.setEnabled(false);
        txtMultaPorDinheiro.setEnabled(false);

        jBCancelar.setEnabled(true);
        jbAlterar.setEnabled(false);
        jbInserir.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbConfirmar.setEnabled(true);
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed

        jbConfirmar.setEnabled(!true);
        txtNomePolitica.setEnabled(!true);
        txtQtdDia.setEnabled(!true);
        txtQtdItens.setEnabled(!true);
        txtMultaPorDinheiro.setEnabled(!true);
        jsMultaEmDias.setEnabled(false);
        txtPesquisar.setEnabled(true);
        jbPesquisar.setEnabled(true);
        jBCancelar.setEnabled(!true);
        limparCampos();
        jbInserir.setEnabled(true);
        jbAlterar.setEnabled(!true);
        jbExcluir.setEnabled(!true);
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        int r = verificarCampos();

        if(flag==1 && r !=1){

            politica.setNome(txtNomePolitica.getText());
            politica.setQtdDeDia(Integer.parseInt(txtQtdDia.getText().toString()));
            politica.setQtdDeLivro(Integer.parseInt(txtQtdItens.getText().toString()));
            politica.setMultaEmDinheiro(Float.parseFloat(txtMultaPorDinheiro.getText()));
            politica.setStatus("Inativa");
            politica.setMultaPorDia(Integer.parseInt(jsMultaEmDias.getText()));
            System.out.println(politica.getMultaPorDia());
            daoPolitica.salvar(politica);

            limparCampos();
            // preencherTabela("SELECT Nome, Qtddias, Qtdlivros, multaEmDias, multaDinheiro, Status " + "FROM politicas " +"WHERE " +"(nome ='" + politica.getPesquisa() + "')");
            preencherTabela("SELECT * FROM `politicas` WHERE Nome LIKE '%" + txtPesquisar.getText()+"%'");
            txtNomePolitica.setEnabled(false);
            txtQtdDia.setEnabled(false);
            txtQtdItens.setEnabled(false);
            txtMultaPorDinheiro.setEnabled(false);
            txtPesquisar.setEnabled(true);
            jbPesquisar.setEnabled(true);
            jbConfirmar.setEnabled(false);
            jsMultaEmDias.setEnabled(false);
        }else if (flag == 2 && r!=1){
            politica.setNome(txtNomePolitica.getText());
            politica.setQtdDeDia(Integer.parseInt(txtQtdDia.getText()));
            politica.setQtdDeLivro(Integer.parseInt(txtQtdItens.getText()));
            politica.setMultaEmDinheiro(Float.parseFloat(txtMultaPorDinheiro.getText()));
            politica.setStatus(jtPolitica.getValueAt(jtPolitica.getSelectedRow(), 5).toString());
            daoPolitica.editar(politica);
            jbInserir.setEnabled(true);
            limparCampos();
            //preencherTabela("SELECT Nome, Qtddias, Qtdlivros, multaEmDias, multaDinheiro, Status " + "FROM politicas " +"WHERE " +"(nome ='" + politica.getPesquisa() + "')");
            preencherTabela("SELECT * FROM `politicas` WHERE Nome LIKE '%" + txtPesquisar.getText()+"%'");
            txtNomePolitica.setEnabled(false);
            txtQtdDia.setEnabled(false);
            txtQtdItens.setEnabled(false);
            txtMultaPorDinheiro.setEnabled(false);
            jsMultaEmDias.setEnabled(false);
            jbConfirmar.setEnabled(false);
        }else if (flag == 3 ){
            politica.setPesquisa(txtNomePolitica.getText());
            BeansPolitica model =  daoPolitica.buscaPolitica(politica);
            String p = model.getStatus();

            if("Inativa".equals(p)){
                daoPolitica.excluir(politica);
                limparCampos();

                preencherTabela("SELECT * FROM `politicas` WHERE Nome LIKE '%" + txtPesquisar.getText()+"%'");
                txtNomePolitica.setEnabled(false);
                txtQtdDia.setEnabled(false);
                txtQtdItens.setEnabled(false);
                txtMultaPorDinheiro.setEnabled(false);

                jbConfirmar.setEnabled(false);
                jbInserir.setEnabled(true);
                jbAlterar.setEnabled(false);
                jbExcluir.setEnabled(false);

            }else if("Ativa".equals(p)){

                JOptionPane.showMessageDialog(null, "Politica de emprestimo em uso! exclusão não realizada ");
            }

        }
    }//GEN-LAST:event_jbConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarPolitica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarPolitica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarPolitica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarPolitica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarPolitica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jSPainelTabela;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JTextField jsMultaEmDias;
    private javax.swing.JTable jtPolitica;
    private javax.swing.JTextField txtMultaPorDinheiro;
    private javax.swing.JTextField txtNomePolitica;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtQtdDia;
    private javax.swing.JTextField txtQtdItens;
    // End of variables declaration//GEN-END:variables
}
